spring:
  datasource:
    url: jdbc:mysql://140.143.225.172:3306/sell?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: /var/log/tomcat/sell.log

